### ISSUE TITLE
Элементы форм и инпут

### ISSUE THREAD

**Issue by Kalinss** [Reniary/task-manager#15]
Сформировать директорию FormElements в Components

Перенести туда и доработать InputDefault
![image](https://user-images.githubusercontent.com/20497457/141690046-03f17edb-a620-4756-852a-dfb36ffa80ad.png)

Глупый компонент должен отвечать следующим параметрам:
* Иметь возможность принимать значение инпута как с пропса, так и работать с внутренним значением value
* Иметь возможность обрабатывать статус ошибки
* При type search иметь анимированную иконку.
* При onChange должен уведомлять родителя коллбэком о измененном состоянии

**Comment by Reniary** [comment]
+ Иметь возможность принимать значение инпута как с пропса, так и работать с внутренним значением value
+ Иметь возможность обрабатывать статус ошибки
-+ При type search иметь анимированную иконку. (отдельный компонент InputSearch) при onBlur не стирается значение из инпута)
+ При onChange должен уведомлять родителя коллбэком о измененном состоянии
