### ISSUE TITLE
DatePickerInput

### ISSUE THREAD

**Issue by Kalinss** [Reniary/task-manager#16]
Сформировать глупый компонент обертку DatePickerInput, что будет оборачивать InputDefault. И давать возможность вызова виджета календаря.
 
 Требования (Возможно понадобятся доработки InputDefault)
 * При клике на иконку календаря (добить onClickIcon для InputDefault), инпут уведомляет обертку, что будет совершать вызов пикера.
 * При выборе даты с пикера, обертка уведомляет своего родителя об изменении и изменяет значение value на котором завязан InputDefault.
 * При onChange с InputDefaut обертка изменяет value и уведомляет своего родителя

**Comment by Reniary** [comment]
для календаря используется ReactDatepicker
